version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly" }
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: "npm"
    directory: "/CleanArchitectureTemplate/src/WebUI/ClientApp"
    schedule: { interval: "weekly" }
    groups:
      frontend:
        patterns: ["*"]
  - package-ecosystem: "nuget"
    directory: "/CleanArchitectureTemplate"
    schedule: { interval: "weekly" }
    groups:
      dotnet:
        patterns: ["*"]
